### ISSUE TITLE
feature.getPropertyNames is not a function

### ISSUE THREAD

**Issue by bertt** [AnalyticalGraphicsInc/cesium#8114]
I'm trying to get 3D tiles interactivity working on Cesium 1.60, for live sample viewer see
https://geodan.github.io/pg2b3dm/sample_data/index_cesium.html 

Sample code:

```
    var handler = new Cesium.ScreenSpaceEventHandler(viewer.canvas);
    handler.setInputAction(function(movement) {
      var feature = viewer.scene.pick(movement.position);
      if (!Cesium.defined(feature)) {
          return;
      }
      // next line gives: feature.getPropertyNames is not a function
      var propertyNames = feature.getPropertyNames();
  }, Cesium.ScreenSpaceEventType.RIGHT_CLICK);
```

When right clicking on a building there is an exception: 

```
Uncaught TypeError: feature.getPropertyNames is not a function
    at index_cesium.html:27
    at C (Cesium.js:490)
    at b (Cesium.js:490)
    at M (Cesium.js:490)
    at HTMLCanvasElement.n (Cesium.js:490)
```

How can I fix this?

**Comment by bertt** [comment]
ok thanks, the pickedObject.content.featuresLength is indeed 0, now have to figure out why. The b3dm tiles are created with py3dtiles with batching option.
