### ISSUE TITLE
Cesium does not build with npm 1.3.10

### ISSUE THREAD

**Issue by gberaudo** [AnalyticalGraphicsInc/cesium#4080]
There is no compilation error, but the build only takes half a minute and Cesium.js is missing from Build/Cesium. The [build guide](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Documentation/Contributors/BuildGuide/README.md) does not mention a minimal version of npm.

With npm 1.3.10
```
$ npm run minifyRelease

> cesium@1.23.0 minifyRelease /home/gberaudo/cesium
> gulp minifyRelease

[08:31:22] Using gulpfile ~/cesium/gulpfile.js
[08:31:22] Starting 'build'...
[08:31:23] Finished 'build' after 1.25 s
[08:31:23] Starting 'generateStubs'...
[08:31:24] Finished 'generateStubs' after 268 ms
[08:31:24] Starting 'minifyRelease'...
Building Cesium.js
Building Source/Workers/cesiumWorkerBootstrapper.js
Finished Cesium.js
Finished Source/Workers/cesiumWorkerBootstrapper.js
Building Source/ThirdParty/Workers/inflate.js
Finished Source/ThirdParty/Workers/inflate.js
...
[08:32:00] Finished 'minifyRelease' after 36 s
```

Then
$ ls Build/Cesium/
Assets  Widgets

With npm 2.15.5

```
$ npm run minifyRelease

> cesium@1.23.0 minifyRelease /tmp/cesium
> gulp minifyRelease

[08:43:33] Using gulpfile /tmp/cesium/gulpfile.js
[08:43:33] Starting 'build'...
[08:43:33] Finished 'build' after 339 ms
[08:43:33] Starting 'generateStubs'...
[08:43:33] Finished 'generateStubs' after 46 ms
[08:43:33] Starting 'minifyRelease'...
Building Cesium.js
Building Source/Workers/cesiumWorkerBootstrapper.js
Building Source/Workers/transferTypedArrayTest.js
Building Source/ThirdParty/Workers/deflate.js
Building Source/ThirdParty/Workers/inflate.js
Finished Source/Workers/transferTypedArrayTest.js
Finished Source/Workers/cesiumWorkerBootstrapper.js
Finished Source/ThirdParty/Workers/deflate.js
Finished Source/ThirdParty/Workers/inflate.js
Building Source/Workers/combineGeometry.js
Building Source/Workers/createBoxGeometry.js
Building Source/Workers/createBoxOutlineGeometry.js
Building Source/Workers/createCircleGeometry.js
...
```

**Comment by hpinkos** [comment]
Thanks @gberaudo!  We all use node version 4.2.2

@mramato is this a bug or do we need to specify a version of Node in the build guide?

**Comment by mramato** [comment]
We should specify Node 4.x or newer in the build guide.  All earlier versions are soon to be end-of-life.

**Comment by gberaudo** [comment]
Thanks
