### PR TITLE
Fix viewerCesiumInspectorMixin

### LINKED ISSUE #5323: Cesium Inspector sandcastle example crashes
```
TypeError: viewer.cesiumInspector.viewModel.update is not a function
TypeError: viewer.cesiumInspector.viewModel.update is not a function
    at http://localhost:8080/Source/Widgets/Viewer/viewerCesiumInspectorMixin.js:51:46
    at Event.raiseEvent (http://localhost:8080/Source/Core/Event.js:147:30)
    at render (http://localhost:8080/Source/Scene/Scene.js:2655:27)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:2663:13)
    at CesiumWidget.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:682:25)
    at render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:72:32)
```

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #5323

@tfili

### CODE REVIEW

**Comment by tfili** [comment]
Looks good @hpinkos. Once it goes green I'll merge it.

**Comment by pjcozzi** [comment]
Should this have an update to CHANGES.md since it fixes a GitHub issue?

**Comment by hpinkos** [comment]
The bug wasn't shipped in a release (it was introduced by #5249) so I don't think it needs to be noted in CHANGES.md

**Comment by pjcozzi** [comment]
Gotcha.
